### PR TITLE
feat: ability to enable vim mode

### PR DESCRIPTION
**Pull request by johnny243**
`vim mode` is enabled/disabled globally via a button

image

---

Any suggestions on the look of the button are welcome!

### CODE REVIEW

**Comment by mobitar** [comment]
How does the enable button look?

**Comment by johnny243** [comment]
> How does the enable button look?

Peek 2021-02-06 17-54

**Comment by johnny243** [comment]
Let me know if this is ok to merge 👍🏽

**Comment by mobitar** [comment]
It is, but I don’t think we should release to prod until we add stylekit.

**Comment by johnny243** [comment]
Right. I will merge this to `develop`, create a PR for stylekit and then we can release to prod

**Pull request merged**
